# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('H', 'Hamburger'), ('B', 'Bebida'), ('A', 'Acompanhamento'), ('B', 'Brinde')], default='H', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Combo')),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='componentes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Componentes'),
        ),
    ]
