# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='codigo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(default='Cliente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
