# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160608_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='nome',
            field=models.CharField(choices=[('Combo com Refrigerante', 'Simples com refrigerante'), ('Combo com Suco', 'Simples com suco'), ('Combo com Suco e batata', 'Completo com suco'), ('Combo com Refrigerante e batata', 'Completo com refrigerante'), ('Combo com Suco, batata e brinde', 'Completo com suco e brinde'), ('Combo com Refrigerante, batata e brinde', 'Completo com refrigerante e brinde')], default='Combo com Refrigerante', max_length=50),
        ),
    ]
