# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160608_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentes',
            name='tipo',
            field=models.CharField(choices=[('H', 'Hamburger'), ('Be', 'Bebida'), ('A', 'Acompanhamento'), ('Br', 'Brinde')], default='H', max_length=15),
        ),
    ]
